/**
 * Regenerates src/api.generated.ts from the checked-in openapi.json snapshot
 * with a deterministic header.
 *
 * Run: npm run gen:api   (from ui/)
 * Refresh the snapshot first with: npm run spec:dump
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'

const HEADER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 *
 * Regenerate with: npm run gen:api
 * (reads ui/openapi.json; refresh it from a live backend with \`npm run spec:dump\`
 *  — requires the Go toolchain at the repo root: go run ../scripts/openapi-dump)
 * The checked-in openapi.json snapshot means the UI build never needs a
 * running backend; refresh the snapshot when the huma API changes.
 */
`

execFileSync(
  process.platform === 'win32' ? 'npx.cmd' : 'npx',
  ['openapi-typescript', 'openapi.json', '-o', 'src/api.generated.ts'],
  { stdio: 'inherit' },
)

// The generator's default header is replaced with the header above so every
// regeneration byte-matches the checked-in file when the spec is unchanged.
const generated = readFileSync('src/api.generated.ts', 'utf8')
const body = generated.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '')
writeFileSync('src/api.generated.ts', `${HEADER}\n${body}`)
